name:                api
version:             0.1.0.0
github:              "DoctorRyner/try.gimel.io/api"
license:             MIT
author:              "DoctorRyner"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try.gimel.io/api#readme>

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-unused-do-bind
- -Werror=incomplete-patterns
- -F -pgmF=record-dot-preprocessor

default-extensions:
- OverloadedStrings
- LambdaCase
- DataKinds
- DeriveGeneric
- TemplateHaskell
- TypeOperators
- DuplicateRecordFields
- QuasiQuotes

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- bytestring
- lens
- servant
- servant-server
- wai
- warp
- text
- record-hasfield
- servant-swagger
- swagger2


library:
  source-dirs: src

executables:
  api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - api

tests:
  api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - api
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
