name:                api
version:             0.1

dependencies:
- base >= 4.7 && < 5
- record-hasfield
- text

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-unused-do-bind
- -Werror=incomplete-patterns
- -F -pgmF=record-dot-preprocessor

default-extensions:
- OverloadedStrings
- LambdaCase

library:
  source-dirs: src

executables:
  api:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
